version: '3.3'
services:
  postgres:
    container_name: postgres-db
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${PG_LOCAL_PORT}:${PG_PORT}

  app:
    container_name: graph-docker
    image: mavlonovfahriddin/graph-app
    depends_on:
      - postgres
    restart: unless-stopped  # fixed typo here
    ports:
      - ${API_LOCAL_PORT}:${API_PORT}  # added missing space

    environment:
      - API_PORT=${API_PORT}
      - API_LOCAL_PORT=${API_LOCAL_PORT}
      - PG_CONNECTION=${PG_CONNECTION}
      - PG_USERNAME=${PG_USERNAME}
      - PG_PORT=${PG_PORT}
      - PG_LOCAL_PORT=${PG_LOCAL_PORT}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
      - PG_HOST=postgres
